<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="POU" Id="{fb12fcb4-55f7-4d9f-9751-eaa4648ce7c7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION POU : eq2hor
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>