<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Rad2Deg" Id="{a320a001-4311-4bc7-9be8-f3dc9b2d884e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Rad2Deg : LREAL
VAR_INPUT
	rad: LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Rad2Deg := rad / PI * 180.0;]]></ST>
    </Implementation>
    <LineIds Name="Rad2Deg">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>