<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="JD2JEPOCH" Id="{d6b96f58-e0c7-4838-aa13-cd616af573e4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION JD2JEPOCH : LREAL
VAR_INPUT
	jd			: LREAL;	// Julian date
END_VAR
VAR CONSTANT
	jd2000		: LREAL := 2451545.0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Julian epoch (equinox) of jd, e.g. for precession
JD2JEPOCH := (jd - jd2000)/365.25 + 2000.0;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>